<a href="https://colab.research.google.com/github/mateuscsco/Formacao_Data_Science/blob/main/Pandas/Extras/Criando_Estruturas_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = [1, 2, 3, 4, 5]#criamos uma array unidimensional
s = pd.Series(data)#tornamos a array uma Serie atribuida a s
s#visualizamos que, para a Serie é tb atribuída uma contagem de index

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
index = ['Linha' + str(i) for i in range(5)]#realiza um contador, de 0 a 4, por meio do for, o str(i) tona o i uma string que é concatenada à 'Linha'
index

['Linha0', 'Linha1', 'Linha2', 'Linha3', 'Linha4']

In [ ]:
s = pd.Series(data = data, index = index)#podemos passar o data e o index para a Series como "argumentos" para a criação da Series
s

Linha0    1
Linha1    2
Linha2    3
Linha3    4
Linha4    5
dtype: int64

In [ ]:
s1 = s + 2#podemos realizar operações matemáticas com a Serie, como no caso, somando 2 aos valores das rows
s1

Linha0    3
Linha1    4
Linha2    5
Linha3    6
Linha4    7
dtype: int64

In [ ]:
s2 = s + s1# podemos até mesmo realizar somas entre Series
s2

Linha0     4
Linha1     6
Linha2     8
Linha3    10
Linha4    12
dtype: int64

In [ ]:
#@title Array de arrays
data = [[1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]]

In [ ]:
df1 = pd.DataFrame(data=data)#criando um DataFrame
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
index = ['Linha' + str(i) for i in range(3)]
columns = ['Coluna' + str(i) for i in range(3)]
df1=pd.DataFrame(data = data, index = index, columns = columns)#utilizando argumentos de index e columns
df1

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [ ]:
columns = ['Coluna' + str(i) for i in range(3)]
df2 = pd.DataFrame(data = data, index = index, columns = columns)
df2

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [ ]:
data = {'Coluna0': {'Linha0': 1, 'Linha1': 4, 'Linha2': 7},#obtendo o mesmo DataFrame com dicionário
        'Coluna1': {'Linha0': 2, 'Linha1': 5, 'Linha2': 8},
        'Coluna2': {'Linha0': 3, 'Linha1': 6, 'Linha2': 9}}
df3 = pd.DataFrame(data)
df3

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [ ]:
data = [(1, 2, 3), # obtendo a mesma Data Frame com tuplas
        (4, 5, 6), 
        (7, 8, 9)]

In [ ]:
df4 = pd.DataFrame(data = data, index = index, columns = columns)
df4

        Coluna0  Coluna1  Coluna2
Linha0        1        2        3
Linha1        4        5        6
Linha2        7        8        9

In [ ]:
df1[df1 > 0] = 'A' #transformando termos maiores que 0 em A
df1

       Coluna0 Coluna1 Coluna2
Linha0       A       A       A
Linha1       A       A       A
Linha2       A       A       A

In [ ]:
df2[df2 > 0] = 'B' #transformando termos maiores que 0 em B
df2

       Coluna0 Coluna1 Coluna2
Linha0       B       B       B
Linha1       B       B       B
Linha2       B       B       B

In [ ]:
df3[df3 > 0] = 'C'#transformando termos maiores que 0 em C
df3

       Coluna0 Coluna1 Coluna2
Linha0       C       C       C
Linha1       C       C       C
Linha2       C       C       C

In [ ]:
df4 = pd.concat([df1, df2, df3]) # concatenando as DataFrames no axis = 0
df4

       Coluna0 Coluna1 Coluna2
Linha0       A       A       A
Linha1       A       A       A
Linha2       A       A       A
Linha0       B       B       B
Linha1       B       B       B
Linha2       B       B       B
Linha0       C       C       C
Linha1       C       C       C
Linha2       C       C       C

In [ ]:
df4 = pd.concat([df1, df2, df3], axis = 1) # concatenando as DataFrames no axis = 1
df4

       Coluna0 Coluna1 Coluna2 Coluna0 Coluna1 Coluna2 Coluna0 Coluna1 Coluna2
Linha0       A       A       A       B       B       B       C       C       C
Linha1       A       A       A       B       B       B       C       C       C
Linha2       A       A       A       B       B       B       C       C       C