<a href="https://colab.research.google.com/github/mateuscsco/Formacao_Data_Science/blob/main/Pandas/Extras/Organizando_DataFrames(Sort).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]#lista de listas

In [ ]:
list('321') #list que recebe string

['3', '2', '1']

In [ ]:
df = pd.DataFrame(data, list('321'), list('ZYX'))#data=data list=index e zyx como columns
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [ ]:
df.sort_index(inplace = True)#m√©todo sort organiza o data frame, no caso, por meio dos index
df

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [ ]:
df.sort_index(inplace = True, axis = 1)#informando o argumento axis, teremos uma nova l√≥gica de organiza√ß√£o, invertendo a ordem pelo label da linha e coluna.:
df

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [ ]:
df.sort_values(by = 'X', inplace = True)#Podemos, ainda, utilizar sort_values() e passar uma ou mais vari√°veis. Como exemplo inicial passaremos o apenas a vari√°vel X.O √≠ndice foi invertido, com base na organiza√ß√£o da vari√°vel X
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [ ]:
df.sort_values(by = ['X','Y'], inplace = True)
df

   X  Y  Z
3  3  2  1
2  6  5  4
1  9  8  7

In [ ]:
df.sort_values(by = '3', axis = 1, inplace = True)#Adicionaremos o termo axis = 1 e especificaremos a linha 3.
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9